#pragma once

#define BOARD_DISP_COUNT 1     /* Waveshare ESP32-S3-Touch-LCD-5B */

/* SD card */
#define BOARD_SD_CLK    GPIO_NUM_NC
#define BOARD_SD_CMD    GPIO_NUM_NC
#define BOARD_SD_D0     GPIO_NUM_NC

/* I2C pins */
#define BOARD_I2C_SCL   GPIO_NUM_9
#define BOARD_I2C_SDA   GPIO_NUM_8

/* I2C Touch */
#define BOARD_DISP_TOUCH_CONTROLLER BOARD_DISP_TOUCH_GT911
#define BOARD_DISP_TOUCH_INT GPIO_NUM_4
#define BOARD_DISP_TOUCH_HRES 800
#define BOARD_DISP_TOUCH_VRES 480

/* I2C display */
#define BOARD_DISP_I2C_CONTROLLER -1
#define BOARD_DISP_I2C_RST  GPIO_NUM_NC
#define BOARD_DISP_I2C_BL   GPIO_NUM_NC
#define BOARD_DISP_I2C_HRES 0
#define BOARD_DISP_I2C_VRES 0

/* SPI display */
#define BOARD_DISP_SPI_CONTROLLER -1
#define BOARD_DISP_SPI_MOSI GPIO_NUM_NC
#define BOARD_DISP_SPI_SCLK GPIO_NUM_NC
#define BOARD_DISP_SPI_CS   GPIO_NUM_NC
#define BOARD_DISP_SPI_DC   GPIO_NUM_NC
#define BOARD_DISP_SPI_RST  GPIO_NUM_NC
#define BOARD_DISP_SPI_BL   GPIO_NUM_NC
#define BOARD_DISP_SPI_HRES 0
#define BOARD_DISP_SPI_VRES 0

/* Parallel display */
#define BOARD_DISP_PARALLEL_CONTROLLER BOARD_DISP_LCD_RA8875
#define BOARD_DISP_PARALLEL_WIDTH   16
#define BOARD_DISP_PARALLEL_DB0     GPIO_NUM_13
#define BOARD_DISP_PARALLEL_DB1     GPIO_NUM_12
#define BOARD_DISP_PARALLEL_DB2     GPIO_NUM_11
#define BOARD_DISP_PARALLEL_DB3     GPIO_NUM_10
#define BOARD_DISP_PARALLEL_DB4     GPIO_NUM_9
#define BOARD_DISP_PARALLEL_DB5     GPIO_NUM_46
#define BOARD_DISP_PARALLEL_DB6     GPIO_NUM_3
#define BOARD_DISP_PARALLEL_DB7     GPIO_NUM_8
#define BOARD_DISP_PARALLEL_DB8     GPIO_NUM_18
#define BOARD_DISP_PARALLEL_DB9     GPIO_NUM_17
#define BOARD_DISP_PARALLEL_DB10    GPIO_NUM_16
#define BOARD_DISP_PARALLEL_DB11    GPIO_NUM_15
#define BOARD_DISP_PARALLEL_DB12    GPIO_NUM_7
#define BOARD_DISP_PARALLEL_DB13    GPIO_NUM_6
#define BOARD_DISP_PARALLEL_DB14    GPIO_NUM_5
#define BOARD_DISP_PARALLEL_DB15    GPIO_NUM_4
#define BOARD_DISP_PARALLEL_CS      GPIO_NUM_NC
#define BOARD_DISP_PARALLEL_DC      GPIO_NUM_37
#define BOARD_DISP_PARALLEL_WR      GPIO_NUM_38
#define BOARD_DISP_PARALLEL_RD      GPIO_NUM_NC
#define BOARD_DISP_PARALLEL_RST     GPIO_NUM_39
#define BOARD_DISP_PARALLEL_WAIT    GPIO_NUM_1
#define BOARD_DISP_PARALLEL_BL      GPIO_NUM_NC
#define BOARD_DISP_PARALLEL_HRES    800
#define BOARD_DISP_PARALLEL_VRES    480
