esp_toml_version = 1.0
firmware_images_url = "https://espzav.github.io/Multiple-LCD-Demo/"

supported_apps = ["MULTIPLE_LCD_DEMO"]

[MULTIPLE_LCD_DEMO]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "multiple_lcd_esp32s3_release_v5_0.bin"
android_app_url = ""
ios_app_url = ""